eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER:http://picklu:8002/eureka/}      

spring:
  profiles: development
  application:
    name: FLIGHT-SERVICE
    admin:
      client:
        url: http://picklu:8004
        username: admin
        password: admin
  rabbitmq:
    addresses: amqp://picklu
  