eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://registry:8000/eureka/}
spring:
  application:
    name: AIRLINE-SERVICE
  rabbitmq:
    addresses: amqp://rabbitmq